---
# AURA Node Role - Metadata

galaxy_info:
  author: AURA Blockchain Team
  description: Ansible role for deploying AURA blockchain nodes with Cosmovisor
  company: AURA Blockchain
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - blockchain
    - cosmos
    - tendermint
    - cometbft
    - cosmovisor
    - validator
    - node
    - aura
    - credentials

dependencies: []
