---
# Handlers for cosmos_exporter role

- name: Cosmos exporter reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Cosmos exporter restart service
  ansible.builtin.service:
    name: aura-cosmos-exporter
    state: restarted
  become: true
